from alpine:latest

RUN apk add cmd:pip3 --no-cache python3-dev \
    && pip3 install --upgrade pip

WORKDIR /app

COPY . /app

RUN pip3 --no-cache-dir install -r requirnments.txt 

EXPOSE 5000

ENTRYPOINT ["python3"]
CMD ["app.py"]
